name: Your Workflow Name

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    env:
      SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
      SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install streamlit
          pip install plotly
          pip install matplotlib
          pip install spotipy
          pip install scikit_learn
          pip install python-dotenv
          pip install requests
          pip install xgboost
          
          

      - name: Run Python script
        run: python finalproject.py
