name: Your Workflow Name

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    env:
      SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
      SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install streamlit
          

      - name: Run Python script
        run: python finalproject.py
